name: rna-data-products
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  - mudata
  - pip:
      - anndata
      - leidenalg
      - manhole
      - pandas
      - pyyaml
      - requests
      - scanpy
      - zarr
      - muon