name: azimuth
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  - mudata
  - pip:
      - scanpy
      - squidpy
      - git+https://github.com/satijalab/panhumanpy.git